/**
 * `pluggy clean`: sweep `bin/` (and optionally generated docs) across the
 * selected workspaces. Build outputs only — IDE files (`.classpath`,
 * `.project`, `.idea/`) are explicitly out of scope; we don't want a
 * wide-cast clean deleting things the user didn't expect.
 */

import { readdir, rm, stat } from "node:fs/promises";
import { join } from "node:path";
import process from "node:process";

import { Argument, Command } from "commander";

import { UserError } from "../errors.ts";
import { bold, dim, emit, log } from "../logging.ts";
import {
  projectStartDir,
  resolveWorkspaceContext,
  selectWorkspaceTargets,
  workspaceListOption,
  type WorkspaceNode,
} from "../workspace.ts";

/** What `pluggy clean [target]` deletes. */
export type CleanTarget = "outputs" | "docs" | "dev" | "cache" | "all";

export interface CleanCommandOptions {
  /** Defaults to `outputs`. */
  target?: CleanTarget;
  workspace?: string[];
  exclude?: string[];
  workspaces?: boolean;
  /** Print paths that would be removed without touching disk. */
  dryRun?: boolean;
  /** Global `--project <path>` flag: resolve the project from this file instead of cwd. */
  project?: string;
  cwd?: string;
}

export interface CleanedEntry {
  workspace: string;
  path: string;
  /** True when the directory existed and was removed (or would be in dry-run). */
  removed: boolean;
}

export interface CleanCommandResult {
  status: "success" | "dry-run";
  exitCode: 0;
  wouldRemove?: string[];
  removed?: string[];
  /** docs/ entries left in place because `pluggy docs` didn't generate them. */
  skippedDocs?: string[];
  entries: CleanedEntry[];
}

export async function runCleanCommand(opts: CleanCommandOptions = {}): Promise<CleanCommandResult> {
  const cwd = opts.cwd ?? process.cwd();
  const context = resolveWorkspaceContext(projectStartDir(opts.project, cwd));
  if (context === undefined) {
    throw new UserError("No pluggy project found. Run this from inside a project directory.", {
      code: "E_CLEAN_NO_PROJECT",
      hint: "Run `pluggy init` to create a new project, or cd into an existing one.",
    });
  }

  const what = opts.target ?? "outputs";
  const targets = selectWorkspaceTargets(context, opts, "clean");
  const entries: CleanedEntry[] = [];
  const skippedDocs: string[] = [];
  const dryRun = opts.dryRun === true;

  if (what === "cache") {
    throw new UserError("Cleaning the global cache is a separate, machine-wide operation.", {
      code: "E_CLEAN_CACHE",
      hint: "Run `pluggy cache clean` (it confirms first), or `pluggy cache prune` to evict only stale entries.",
    });
  }

  for (const target of targets) {
    if (what === "outputs" || what === "all") {
      const binPath = join(target.root, "bin");
      if (!(await pathExists(binPath))) {
        entries.push({ workspace: target.name, path: binPath, removed: false });
      } else {
        if (!dryRun) await removePath(binPath);
        entries.push({ workspace: target.name, path: binPath, removed: true });
      }
    }

    if (what === "docs" || what === "all") {
      await cleanDocs(target, entries, skippedDocs, dryRun);
    }

    if (what === "dev" || what === "all") {
      const devPath = join(target.root, "dev");
      if (!(await pathExists(devPath))) {
        entries.push({ workspace: target.name, path: devPath, removed: false });
      } else {
        if (!dryRun) await removePath(devPath);
        entries.push({ workspace: target.name, path: devPath, removed: true });
      }
    }
  }

  const removedPaths = entries.filter((e) => e.removed).map((e) => e.path);
  const result: CleanCommandResult = {
    status: dryRun ? "dry-run" : "success",
    exitCode: 0,
    entries,
  };
  if (dryRun) {
    result.wouldRemove = removedPaths;
  } else {
    result.removed = removedPaths;
  }
  if (skippedDocs.length > 0) {
    result.skippedDocs = skippedDocs;
  }

  const printSummary = (): void => {
    if (entries.length === 0) {
      log.info(dim("No workspaces selected; nothing to clean."));
      return;
    }
    const verb = dryRun ? "would remove" : "removed";
    if (removedPaths.length === 0) {
      log.info(dim(`${verb}: nothing (no ${what} present)`));
    } else {
      log.heading(
        `${bold("clean")} ${verb} ${removedPaths.length} path${removedPaths.length === 1 ? "" : "s"}`,
      );
      for (const entry of entries) {
        if (!entry.removed) continue;
        log.step(`${entry.workspace}: ${entry.path}`);
      }
    }
    if (skippedDocs.length > 0) {
      log.info(
        dim(
          `docs: left ${skippedDocs.length} entr${skippedDocs.length === 1 ? "y" : "ies"} in place (not generated by \`pluggy docs\`): ${skippedDocs.join(", ")}`,
        ),
      );
    }
  };
  emit(result as unknown as Record<string, unknown>, printSummary);
  return result;
}

/**
 * Remove only the docs subdirectories `pluggy docs` generates
 * (`docs/<name>-<version>/`). Anything else under `docs/` is user content:
 * it stays on disk and is collected into `skipped` for reporting. The
 * `docs/` directory itself goes only when nothing remains inside it.
 */
async function cleanDocs(
  target: WorkspaceNode,
  entries: CleanedEntry[],
  skipped: string[],
  dryRun: boolean,
): Promise<void> {
  const docsDir = join(target.root, "docs");
  let dirEntries;
  try {
    dirEntries = await readdir(docsDir, { withFileTypes: true });
  } catch {
    entries.push({ workspace: target.name, path: docsDir, removed: false });
    return;
  }

  let removedAny = false;
  let keptAny = false;
  for (const entry of dirEntries) {
    const path = join(docsDir, entry.name);
    if (
      entry.isDirectory() &&
      isGeneratedDocsDir(entry.name, target.project.name, target.project.version)
    ) {
      if (!dryRun) await removePath(path);
      entries.push({ workspace: target.name, path, removed: true });
      removedAny = true;
    } else {
      skipped.push(path);
      keptAny = true;
    }
  }
  if (!removedAny) {
    entries.push({ workspace: target.name, path: docsDir, removed: false });
  } else if (!keptAny && !dryRun) {
    await removePath(docsDir);
  }
}

/**
 * True for `<name>-<version>` directory names as `pluggy docs` writes them.
 * `pluggy docs` uses the raw (unvalidated) project.json version, so the
 * workspace's exact `projectVersion` always matches; the shape regex
 * additionally catches dirs left over from earlier version bumps.
 */
function isGeneratedDocsDir(
  entryName: string,
  projectName: string,
  projectVersion: string,
): boolean {
  if (!entryName.startsWith(`${projectName}-`)) return false;
  const version = entryName.slice(projectName.length + 1);
  return version === projectVersion || /^\d+\.\d+\.\d+(-[a-zA-Z0-9]+)?$/.test(version);
}

async function removePath(path: string): Promise<void> {
  try {
    await rm(path, { recursive: true, force: true });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`failed to remove ${path}: ${message}`);
  }
}

async function pathExists(path: string): Promise<boolean> {
  try {
    await stat(path);
    return true;
  } catch {
    return false;
  }
}

/**
 * Factory for the `pluggy clean` commander command.
 *
 * Six things were called "clean": this command, the `--clean` flags on
 * build/test/docs/dev, and `cache clean` — and `clean --docs` deleted the same
 * directory as `docs --clean`, with the tokens transposed. The help footer had
 * become a disambiguation table, which is a naming problem wearing a docs
 * costume. An explicit target replaces it.
 */
export function cleanCommand(): Command {
  return new Command("clean")
    .description("Delete generated output: build artifacts, docs, the dev server, or the cache.")
    .addArgument(
      new Argument("[target]", "What to delete.")
        .choices(["outputs", "docs", "dev", "cache", "all"])
        .default("outputs"),
    )
    .addHelpText(
      "after",
      "\nTargets:\n  outputs  bin/ jars (default)\n  docs     generated docs/<name>-<version>/\n  dev      the dev server directory\n  cache    pluggy's global download cache (all projects)\n  all      everything above except cache\n\nThe --clean flags on build, test, docs, and dev mean \"start this run fresh\"; they don't delete and stop.",
    )
    .option(
      "--workspace <names>",
      "Clean one or more workspaces (repeatable; comma-separated).",
      workspaceListOption,
    )
    .option(
      "--exclude <names>",
      "Exclude workspaces from an all-workspaces clean (repeatable; comma-separated).",
      workspaceListOption,
    )
    .option("--workspaces", "Explicit all-workspaces clean.")
    .option("--dry-run", "Print paths that would be removed without touching disk.")
    .action(async function action(this: Command, target: CleanTarget, options) {
      const globalOpts = this.optsWithGlobals();
      await runCleanCommand({
        target,
        workspace: options.workspace as string[],
        exclude: options.exclude as string[],
        workspaces: options.workspaces === true,
        dryRun: options.dryRun === true,
        project: globalOpts.project,
      });
    });
}
