import { readdir } from "node:fs/promises";
import { mkdir, writeFile } from "node:fs/promises";
import { basename, join, relative, resolve } from "node:path";
import process from "node:process";

import { Command, InvalidArgumentError } from "commander";
import { checkbox, confirm, input } from "@inquirer/prompts";

import defaultConfig from "../defaults/config.yml" with { type: "text" };
import defaultPackage from "../defaults/package.java" with { type: "text" };

import { writeIntellijStub } from "../build/intellij.ts";
import { getPlatform, getRegisteredPlatforms } from "../platform/index.ts";
import { getJavaRange } from "../platform/spigot/buildtools.ts";
import { bold, dim, log } from "../logging.ts";
import { writeFileLF } from "../portable.ts";
import { getCurrentProject, type Project, resolveProjectFile } from "../project.ts";
import { replace } from "../template.ts";

import { getJavaMajor } from "./doctor.ts";
import { parseMcVersion, parsePlatform, parseSemver } from "./parsers.ts";

/**
 * Scaffold a new project at `distDir` from the given `Project` config.
 *
 * Writes:
 *   - `project.json`
 *   - `src/config.yml`
 *   - `src/<package>/<Class>.java`
 *   - `.gitignore` (build outputs and regenerated IDE files)
 *   - `<name>.iml` + `.idea/` (IntelliJ stub linked to Eclipse files)
 *
 * Throws if `project.main` is unset or any of the writes fail.
 */
export async function generateProject(distDir: string, project: Project): Promise<void> {
  const main = project.main;
  if (!main) {
    throw new Error("generateProject requires project.main to be set");
  }

  try {
    await mkdir(distDir, { recursive: true });
  } catch (e) {
    throw new Error(`Failed to create project directory: ${(e as Error).message}`);
  }

  const projectFilePath = join(distDir, "project.json");
  try {
    await writeFile(projectFilePath, JSON.stringify(project, null, 2));
  } catch (e) {
    throw new Error(`Failed to write project file: ${(e as Error).message}`);
  }

  const replacementProject = {
    project: {
      ...project,
      className: main.split(".").pop() || "Main",
      packageName: main.split(".").slice(0, -1).join("."),
    },
  };

  const configFilePath = join(distDir, "src", "config.yml");
  try {
    await mkdir(join(distDir, "src"), { recursive: true });
    await writeFile(configFilePath, replace(defaultConfig, replacementProject));
  } catch (e) {
    throw new Error(`Failed to write config file: ${(e as Error).message}`);
  }

  const mainClassPath = join(distDir, "src", main.replace(/\./g, "/") + ".java");
  try {
    await mkdir(join(distDir, "src", ...main.split(".").slice(0, -1)), { recursive: true });
    await writeFile(mainClassPath, replace(defaultPackage, replacementProject));
  } catch (e) {
    throw new Error(`Failed to write main class file: ${(e as Error).message}`);
  }

  // Default `.gitignore`. `.classpath` and `.project` are regenerated by
  // every build with absolute paths to the user's local cache, so committing
  // them poisons collaborators' clones with `/Users/<me>/...` references.
  // Same logic for build outputs and IntelliJ per-machine state.
  try {
    await writeFileLF(
      join(distDir, ".gitignore"),
      [
        "# pluggy build outputs",
        ".pluggy-build/",
        "bin/",
        "",
        "# Regenerated by `pluggy build` — contain machine-local paths",
        ".classpath",
        ".project",
        "",
      ].join("\n"),
    );
  } catch (e) {
    throw new Error(`Failed to write .gitignore: ${(e as Error).message}`);
  }

  // IntelliJ stub: lets users open the folder directly in IntelliJ without
  // running the Eclipse import wizard or remembering to tick "Link to Eclipse
  // files". Other IDEs ignore `.idea/` and `<name>.iml` entirely.
  try {
    await writeIntellijStub(distDir, project);
  } catch (e) {
    throw new Error(`Failed to write IntelliJ stub: ${(e as Error).message}`);
  }
}

/**
 * Pick the newest version from `candidates` that the user's installed Java
 * can compile. Spigot/Bukkit run BuildTools locally, which silently fails
 * (e.g. decompile output missing) when the Minecraft version's `javaVersions`
 * window excludes the user's JDK — so we probe the first few candidates and
 * skip any whose declared range doesn't include `javaMajor`. Falls through
 * to `candidates[0]` when Java can't be detected or no metadata is usable.
 */
async function pickCompatibleVersion(candidates: string[], platforms: string[]): Promise<string> {
  const fallback = candidates[0];
  if (!platforms.includes("spigot") && !platforms.includes("bukkit")) return fallback;

  const javaMajor = await getJavaMajor().catch(() => undefined);
  if (javaMajor === undefined) return fallback;

  for (const candidate of candidates.slice(0, 10)) {
    const range = await getJavaRange(candidate);
    if (range === undefined) continue;
    const [minJava, maxJava] = range;
    if (javaMajor >= minJava && javaMajor <= maxJava) return candidate;
  }
  return fallback;
}

function deriveClassName(name: string): string {
  return name
    .split(/[-_]/)
    .map((part) => (part ? part.charAt(0).toUpperCase() + part.slice(1) : ""))
    .join("");
}

/** Factory for the `pluggy init` commander command. */
export function initCommand(): Command {
  return new Command("init")
    .description(
      "Initialize a new project with interactive prompts.\n\nIf you want to skip prompts and use defaults, use the -y option.\nIt's recommended to use --main <main> to specify the main class name.",
    )
    .argument("[path]", "Target directory for the new project.")
    .option("--name <name>", "Project name.")
    .option("--version <version>", "Project version.", parseSemver)
    .option("--description <description>", "Project description.")
    .option("--main <main>", "Main class name.")
    .option(
      "--platform <platform>",
      "Target platform, repeatable (default: paper).",
      (val: string, prev: string[]) => {
        const id = parsePlatform(val);
        return prev.includes(id) ? prev : [...prev, id];
      },
      [] as string[],
    )
    .option("--mc-version <version>", "Minecraft version for compatibility.", parseMcVersion)
    .option("-y, --yes", "Skip prompts and use defaults.")
    .addHelpText(
      "after",
      `\nExamples:\n  $ pluggy init --platform paper --platform velocity\n  $ pluggy init --platform spigot --mc-version 1.21.8`,
    )
    .action(async function action(this: Command, path: string | undefined, options) {
      const globalOpts = this.optsWithGlobals();
      const interactive = !options.yes && !globalOpts.json && process.stdout.isTTY;

      let currentProject = getCurrentProject();
      if (globalOpts.project) {
        currentProject = resolveProjectFile(globalOpts.project);
        if (!currentProject) throw new Error(`Project file not found at ${globalOpts.project}`);
      }

      const TARGET_PATH = resolve(process.cwd(), path || ".");

      // Single guard for non-empty dir or existing project
      let warned = false;
      try {
        const entries = await readdir(TARGET_PATH);
        if (entries.length > 0) warned = true;
      } catch (err) {
        if ((err as NodeJS.ErrnoException).code !== "ENOENT") throw err;
      }
      if (!warned && currentProject) warned = true;

      if (warned && globalOpts.json && !options.yes) {
        const reason = currentProject
          ? `"${relative(process.cwd(), currentProject.projectFile)}" already exists`
          : `"${TARGET_PATH}" is not empty`;
        throw new Error(`${reason}. Use --yes to overwrite.`);
      }

      if (warned && interactive) {
        const message = currentProject
          ? `"${relative(process.cwd(), currentProject.projectFile)}" already exists. Overwrite?`
          : `"${TARGET_PATH}" is not empty. Continue?`;
        const ok = await confirm({ message, default: false });
        if (!ok) {
          log.info("Aborted.");
          return;
        }
      }

      // Name
      const defaultName = basename(TARGET_PATH);
      const projectName =
        options.name ??
        (path
          ? basename(TARGET_PATH)
          : interactive
            ? await input({ message: "Project name", default: defaultName })
            : defaultName);

      if (!/^[a-zA-Z0-9_-]+$/.test(projectName)) {
        throw new InvalidArgumentError(
          `Invalid project name: "${projectName}". Only alphanumeric characters, underscores, and hyphens are allowed.`,
        );
      }

      // Platforms
      const registeredPlatforms = getRegisteredPlatforms();
      const platforms: string[] =
        options.platform.length > 0
          ? options.platform
          : interactive
            ? await checkbox({
                message: "Target platforms",
                choices: registeredPlatforms.map((p) => ({
                  value: p,
                  name: p,
                  checked: p === "paper",
                })),
                validate: (vals) => vals.length > 0 || "Select at least one platform.",
              })
            : ["paper"];

      const primaryPath = getPlatform(platforms[0]).descriptor.path;
      const alien = platforms.find((p) => getPlatform(p).descriptor.path !== primaryPath);
      if (alien) {
        throw new InvalidArgumentError(
          `Platform "${alien}" cannot be combined with "${platforms[0]}" — they target different plugin families ` +
            `("${platforms[0]}" writes "${primaryPath}", "${alien}" writes "${getPlatform(alien).descriptor.path}"). ` +
            `Proxy platforms like velocity, waterfall, and travertine each need their own project.`,
        );
      }

      // Main class
      const className = deriveClassName(projectName) || "Main";
      const derivedMain = `com.example.${className}`;
      const projectMain =
        options.main ??
        (interactive ? await input({ message: "Main class", default: derivedMain }) : derivedMain);

      if (!projectMain || !/^[a-zA-Z0-9_.]+$/.test(projectMain) || !projectMain.includes(".")) {
        throw new InvalidArgumentError(
          `Invalid main class: "${projectMain}". It must be a valid Java classpath (e.g., com.example.Main).`,
        );
      }

      // Resolve the Minecraft version for compatibility
      let versions: string[];
      if (options.mcVersion) {
        versions = [options.mcVersion];
      } else {
        if (!globalOpts.json) log.info(`Fetching latest versions…`);
        const versionLists = await Promise.all(
          platforms.map(async (p) => ({
            platform: p,
            versions: await getPlatform(p).getVersions(),
          })),
        );
        const common =
          versionLists.reduce<string[] | null>((acc, { versions: vs }) => {
            if (acc === null) return vs;
            const set = new Set(vs);
            return acc.filter((v) => set.has(v));
          }, null) ?? [];
        if (common.length === 0) {
          throw new Error(
            `No compatible Minecraft version found across platforms: ${platforms.join(", ")}. ` +
              `Try selecting fewer platforms or specifying a version manually with --mc-version.`,
          );
        }
        versions = [await pickCompatibleVersion(common, platforms)];
      }

      const INITIAL_PROJECT: Project = {
        name: projectName,
        version: options.version || "1.0.0",
        description: options.description || "A simple Minecraft plugin",
        main: projectMain,
        compatibility: {
          versions,
          platforms,
        },
      };

      await generateProject(TARGET_PATH, INITIAL_PROJECT);

      if (globalOpts.json) {
        console.log(
          JSON.stringify(
            { status: "success", project: INITIAL_PROJECT, dir: TARGET_PATH },
            null,
            2,
          ),
        );
        return;
      }

      log.success(`Project ${bold(`"${INITIAL_PROJECT.name}"`)} initialized`);

      const isCurrentDir = TARGET_PATH === resolve(process.cwd());
      console.log();
      console.log(dim("  Next steps:"));
      if (!isCurrentDir) console.log(dim(`    cd ${relative(process.cwd(), TARGET_PATH)}`));
      console.log(dim("    pluggy dev"));
    });
}
