package ${project.packageName}.sponge;

import ${project.packageName}.api.PluginApi;
import ${project.packageName}.core.PluginCore;

import com.google.inject.Inject;

import org.apache.logging.log4j.Logger;
import org.spongepowered.api.event.Listener;
import org.spongepowered.api.event.lifecycle.ConstructPluginEvent;
import org.spongepowered.plugin.PluginContainer;
import org.spongepowered.plugin.builtin.jvm.Plugin;

/**
 * Sponge entry point. The sponge_plugins.json descriptor is generated by
 * pluggy from this workspace's `main` field and the {@code @Plugin} id.
 * The api + core jars are shaded into this jar at build time.
 */
@Plugin("${project.spongeId}")
public class ${project.className}Sponge {

    private final PluginContainer container;
    private final Logger logger;
    private PluginApi api;

    @Inject
    public ${project.className}Sponge(final PluginContainer container, final Logger logger) {
        this.container = container;
        this.logger = logger;
    }

    @Listener
    public void onConstructPlugin(final ConstructPluginEvent event) {
        this.api = new PluginCore(container.metadata().version().toString(), "Sponge");
        logger.info("${project.name} v{} enabled on {}", api.version(), api.platformName());
    }
}
