/**
 * Compile the dev agent with plain `javac` (no Gradle), jar it, and embed it
 * base64 into `src/dev/agent-jar.generated.ts` so the compiled pluggy binary
 * ships it. Run with `bun agent/build.ts` whenever the Java sources change.
 */

import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = dirname(here);
const srcDir = join(here, "src");
const buildDir = join(here, "build");
const classesDir = join(buildDir, "classes");
const jarPath = join(buildDir, "pluggy-agent.jar");
const generated = join(repo, "src", "dev", "agent-jar.generated.ts");

function javaSources(dir: string): string[] {
  const out: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...javaSources(full));
    else if (entry.name.endsWith(".java")) out.push(full);
  }
  return out;
}

function run(cmd: string, args: string[]): void {
  const result = spawnSync(cmd, args, { stdio: "inherit" });
  if (result.status !== 0) {
    throw new Error(`${cmd} exited with ${result.status ?? result.signal}`);
  }
}

rmSync(buildDir, { recursive: true, force: true });
mkdirSync(classesDir, { recursive: true });

// Java 8 bytecode so the agent attaches to old-MC dev servers too.
run("javac", ["--release", "8", "-Xlint:all,-options", "-d", classesDir, ...javaSources(srcDir)]);
run("jar", [
  "--create",
  "--file",
  jarPath,
  "--manifest",
  join(here, "manifest.mf"),
  "-C",
  classesDir,
  ".",
]);

const bytes = readFileSync(jarPath);
const sha = createHash("sha256").update(bytes).digest("hex");
writeFileSync(
  generated,
  [
    "// Generated by agent/build.ts — do not edit by hand.",
    "/** SHA-256 of the embedded jar; also its cache filename discriminator. */",
    `export const AGENT_JAR_SHA256 = ${JSON.stringify(sha)};`,
    `export const AGENT_JAR_BASE64 =\n  ${JSON.stringify(bytes.toString("base64"))};`,
    "",
  ].join("\n"),
);

spawnSync("vp", ["fmt", generated], { stdio: "ignore" });

console.log(`built ${jarPath} (${bytes.length} bytes) → ${generated}`);
