/**
 * HotswapAgent integration for `pluggy dev`.
 *
 * Three responsibilities:
 *   1. Provision the HotswapAgent JAR into the user cache.
 *   2. Render `hotswap-agent.properties` so HA watches the build's exploded
 *      classes directory (`.pluggy-build/<hash>/`) and redefines classes in
 *      place when javac rewrites them.
 *   3. Expose a category-shaped watcher (`hotswap.start`) that taps the
 *      server's stdout for HA's success/failure markers and surfaces the
 *      outcome to the dev loop's fallback chain.
 *
 * The agent JAR alone allows method-body changes; pair with a JBR `java`
 * (see `./jbr.ts`) and `-XX:+AllowEnhancedClassRedefinition` for the full
 * DCEVM-grade redefinition (new methods, fields, supertype changes).
 */

import type { ChildProcess } from "node:child_process";
import { existsSync } from "node:fs";
import { mkdir, rename, writeFile } from "node:fs/promises";
import { join } from "node:path";

import { log } from "../logging.ts";
import { toPosixPath } from "../portable.ts";
import { getCachePath } from "../project.ts";

/**
 * Pinned HotswapAgent release. Bump deliberately — agent log markers and
 * config keys can shift between majors and `wait()` parses them.
 */
export const HOTSWAP_AGENT_VERSION = "2.0.3";

const AGENT_RELEASE_URL = (version: string): string =>
  `https://github.com/HotswapProjects/HotswapAgent/releases/download/RELEASE-${version}/hotswap-agent-${version}.jar`;

/** Cached path to the HotswapAgent JAR (download on miss). */
export async function ensureAgent(version = HOTSWAP_AGENT_VERSION): Promise<string> {
  const cacheDir = join(getCachePath(), "agents");
  const dest = join(cacheDir, `hotswap-agent-${version}.jar`);
  if (existsSync(dest)) return dest;

  await mkdir(cacheDir, { recursive: true });
  const url = AGENT_RELEASE_URL(version);
  log.info(`hotswap: downloading HotswapAgent ${version}…`);
  const res = await fetch(url);
  if (!res.ok) {
    throw new Error(`hotswap: agent download failed (${res.status} ${res.statusText}) — ${url}`);
  }
  const tmp = `${dest}.partial`;
  await writeFile(tmp, new Uint8Array(await res.arrayBuffer()));
  await rename(tmp, dest);
  log.debug(`hotswap: cached agent at ${dest}`);
  return dest;
}

export interface PropertiesFileOptions {
  /** Absolute path to the build's exploded classes directory. */
  classesDir: string;
  /** `info` is the default; `debug` for verbose markers in playground testing. */
  logLevel?: "error" | "warning" | "info" | "debug" | "trace";
}

/**
 * Render a `hotswap-agent.properties` file.
 *
 * HotswapAgent reads this from each classloader's resources and applies the
 * config to *that* classloader only. We bundle it into the user's plugin JAR
 * (via `BuildOptions.extraStagingFiles`) so HA only attaches the staging
 * directory to the plugin's own classloader. Putting the file on the boot
 * classpath instead would leak `extraClasspath` into the system classloader
 * and Bukkit's `JavaPlugin requires to be created by a valid classloader`
 * guard would fail (parent-first delegation finds the staging-dir copy).
 */
export function renderPropertiesFile(opts: PropertiesFileOptions): string {
  const level = opts.logLevel ?? "info";
  // Java properties files use `\` as an escape, so a Windows path like
  // `C:\Users\…\.pluggy-build\abc` would parse as `C:Users….pluggy-buildabc`.
  // Forward slashes work on every OS — Java's `File` accepts them on Windows.
  const classes = toPosixPath(opts.classesDir);
  return [
    "# Generated by pluggy — do not edit by hand.",
    "# Regenerated on every `pluggy dev` start.",
    `LOGGER=${level}`,
    `extraClasspath=${classes}`,
    "autoHotswap=true",
    // HotswapAgent ships dozens of framework integrations (Spring, Hibernate,
    // JEE, ...). For Bukkit/Paper plugins they're all noise that throws
    // `InvocationTargetException` while trying to instrument unrelated
    // classes. Disable everything except the core class-redefinition path.
    `disabledPlugins=${DISABLED_HA_PLUGINS.join(",")}`,
    "",
  ].join("\n");
}

/**
 * HotswapAgent framework plugins irrelevant to Bukkit/Paper plugin
 * development — keeping them on emits ERROR-level transform warnings on
 * every server start. The core (ClassInitPlugin, AnonymousClassPatch,
 * JdkPlugin, Hotswapper, WatchResources) is left enabled.
 */
const DISABLED_HA_PLUGINS = [
  "Hibernate",
  "HibernateJakarta",
  "Hibernate3",
  "Hibernate3JPA",
  "Spring",
  "SpringBoot",
  "Jersey1",
  "Jersey2",
  "Jetty",
  "Tomcat",
  "ZK",
  "Logback",
  "Log4j2",
  "MyFaces",
  "Mojarra",
  "Omnifaces",
  "ELResolver",
  "WildFlyELResolver",
  "OsgiEquinox",
  "Owb",
  "OwbJakarta",
  "Proxy",
  "WebObjects",
  "Weld",
  "WeldJakarta",
  "JBossModules",
  "ResteasyRegistry",
  "Deltaspike",
  "DeltaspikeJakarta",
  "GlassFish",
  "Weblogic",
  "Vaadin",
  "Wicket",
  "CxfJAXRS",
  "FreeMarker",
  "Undertow",
  "MyBatis",
  "MyBatisPlus",
  "IBatis",
  "JacksonPlugin",
  "Idea",
  "Thymeleaf",
  "Velocity",
  "Sponge",
];

/**
 * Build the JVM argument prefix that turns a vanilla `java` invocation into a
 * HotswapAgent-attached one. Returns args in the order they should appear.
 */
export function agentJvmArgs(input: { agentJarPath: string }): string[] {
  return [
    `-javaagent:${input.agentJarPath}`,
    "-XX:+AllowEnhancedClassRedefinition",
    // HotswapAgent uses internal reflection on URLClassLoader/URLClassPath
    // to splice the build's classes dir into the plugin's own classloader.
    // The module system slammed the door on that in Java 17 — these
    // `--add-opens` flags re-open exactly the surface HA pokes at, no more.
    "--add-opens=java.base/java.lang=ALL-UNNAMED",
    "--add-opens=java.base/jdk.internal.loader=ALL-UNNAMED",
    "--add-opens=java.base/java.net=ALL-UNNAMED",
  ];
}

/**
 * Outcome of a single hotswap attempt. The dev loop chooses its fallback
 * strategy based on which value comes back.
 */
export type HotswapOutcome = "reloaded" | "failed" | "timeout";

export interface StartHotswapOptions {
  child: ChildProcess;
  /** Per-attempt timeout. Default 4000ms — generous to absorb slow disks. */
  timeoutMs?: number;
}

/**
 * Result of `hotswap.start(child)` — single-call backbone for the dev loop.
 *
 * Two-step contract: call `arm()` *before* triggering the rebuild, then
 * `await wait()` after the rebuild completes. Splitting them closes a race —
 * HA's filesystem watcher can emit `RELOAD` while the dev loop is still
 * inside `buildProject`, so any data arriving in that window must be
 * retained for the upcoming `wait()` call instead of dropped.
 *
 * `arm()` clears any buffered data from the previous attempt and starts
 * retaining incoming chunks. `wait()` resolves with the first match in the
 * buffer (or the first one to arrive after subscribing), or `"timeout"`
 * if neither happens before `timeoutMs`. Each arm/wait pair is independent.
 *
 * `stop()` detaches all listeners and is idempotent.
 */
export interface HotswapWatcher {
  arm(): void;
  wait(): Promise<HotswapOutcome>;
  stop(): void;
}

// HA's success marker is the `RELOAD` log level fired right before it calls
// `Instrumentation.redefineClasses()`. The redefinition is synchronous and
// silent on success — failures show up as exceptions on the same thread.
const SUCCESS_RE = /HOTSWAP\s+AGENT.*\bRELOAD\b.*Reloading\s+classes/i;
// Narrow to JVMTI-side rejections of an actual redefinition. HA itself emits
// ERROR-level logs for unrelated framework-plugin transformer issues
// (Log4j2, Jackson, JdkPlugin, …) that aren't hotswap failures — matching
// `HOTSWAP AGENT.*ERROR` here would false-positive on those.
const FAILURE_RE =
  /class\s+redefinition\s+failed|cannot\s+redefine|UnsupportedOperationException.*redefin/i;

/**
 * Attach a stdout/stderr line tap to the running JVM and surface HotswapAgent
 * markers as a single `wait()`-able outcome. Stays out of the way otherwise:
 * the existing pipe to `process.stdout` is preserved so the user still sees
 * the server log unchanged.
 */
export function start(opts: StartHotswapOptions): HotswapWatcher {
  const { child } = opts;
  const timeoutMs = opts.timeoutMs ?? 4000;

  const buffers = { stdout: "", stderr: "" };
  // Match this attempt's outcome — sticks once set so `wait()` can pick it up
  // even if the marker arrived between `arm()` and `wait()`.
  let bufferedOutcome: HotswapOutcome | undefined;
  let armed = false;

  let pendingResolve: ((outcome: HotswapOutcome) => void) | undefined;
  let pendingTimer: NodeJS.Timeout | undefined;

  const tryMatch = (line: string): HotswapOutcome | undefined => {
    if (SUCCESS_RE.test(line)) return "reloaded";
    if (FAILURE_RE.test(line)) return "failed";
    return undefined;
  };

  const finishWait = (outcome: HotswapOutcome): void => {
    if (pendingTimer !== undefined) {
      clearTimeout(pendingTimer);
      pendingTimer = undefined;
    }
    const r = pendingResolve;
    pendingResolve = undefined;
    armed = false;
    bufferedOutcome = undefined;
    if (r !== undefined) r(outcome);
  };

  const onChunk =
    (which: "stdout" | "stderr") =>
    (chunk: Buffer | string): void => {
      if (!armed) return;
      buffers[which] += chunk.toString();
      let nl = buffers[which].indexOf("\n");
      while (nl !== -1) {
        const line = buffers[which].slice(0, nl);
        buffers[which] = buffers[which].slice(nl + 1);
        const outcome = tryMatch(line);
        if (outcome !== undefined) {
          // If `wait()` is already pending, deliver immediately. Otherwise
          // remember the outcome for the next `wait()` call — closes the
          // race where HA fires `RELOAD` before the dev loop subscribes.
          if (pendingResolve !== undefined) {
            finishWait(outcome);
          } else {
            bufferedOutcome = outcome;
          }
          return;
        }
        nl = buffers[which].indexOf("\n");
      }
    };

  const onStdout = onChunk("stdout");
  const onStderr = onChunk("stderr");

  child.stdout?.on("data", onStdout);
  child.stderr?.on("data", onStderr);

  let stopped = false;

  return {
    arm(): void {
      if (stopped) return;
      buffers.stdout = "";
      buffers.stderr = "";
      bufferedOutcome = undefined;
      armed = true;
    },
    wait(): Promise<HotswapOutcome> {
      if (stopped) return Promise.resolve("timeout");
      // Caller forgot to arm — be lenient and arm now (matches no buffered
      // marker, just waits fresh). Tests rely on this.
      if (!armed) {
        buffers.stdout = "";
        buffers.stderr = "";
        bufferedOutcome = undefined;
        armed = true;
      }
      // A marker that arrived between arm() and wait() resolves immediately.
      if (bufferedOutcome !== undefined) {
        const o = bufferedOutcome;
        bufferedOutcome = undefined;
        armed = false;
        return Promise.resolve(o);
      }
      return new Promise<HotswapOutcome>((resolvePromise) => {
        pendingResolve = resolvePromise;
        pendingTimer = setTimeout(() => finishWait("timeout"), timeoutMs);
        pendingTimer.unref?.();
      });
    },
    stop(): void {
      if (stopped) return;
      stopped = true;
      child.stdout?.removeListener("data", onStdout);
      child.stderr?.removeListener("data", onStderr);
      if (pendingTimer !== undefined) {
        clearTimeout(pendingTimer);
        pendingTimer = undefined;
      }
      if (pendingResolve !== undefined) {
        const r = pendingResolve;
        pendingResolve = undefined;
        r("timeout");
      }
    },
  };
}
